CREATE TABLE ingressos (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo               VARCHAR(30)  NOT NULL UNIQUE,
    codigo_autenticacao  VARCHAR(32)  NOT NULL UNIQUE,
    pedido_id            BIGINT       NOT NULL UNIQUE,
    usuario_id           BIGINT       NOT NULL,
    criado_em            TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_ingressos_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos(id),

    CONSTRAINT fk_ingressos_usuario
        FOREIGN KEY (usuario_id) REFERENCES users(id)
);

CREATE INDEX idx_ingressos_usuario_id ON ingressos(usuario_id);
CREATE INDEX idx_ingressos_criado_em  ON ingressos(criado_em);
